#!/usr/bin/env bash

# Wrapper version
VERSION=0.1.3

#####################################################################
# steam-wrapper
# Packaged by: pyamsoft <pyam.soft@gmail.com>
#####################################################################

LOGDIR="$HOME/.steam-wrapper/"
LOG="$LOGDIR/steam-wrapper.log"

# Create the log directory
mkdir -p $LOGDIR

# Log opening
if [[ $DEBUG -eq 1 ]]; then
	echo "steam-wrapper[$VERSION]: Launched on $(date +%Y-%m-%d) at $(date +%R) [$(date +%r)]" >> $LOG
fi

if [[ -f $HOME/.steam-wrapper/steam-wrapper.conf ]]; then
	source $HOME/.steam-wrapper/steam-wrapper.conf
	echo -n "steam-wrapper[$VERSION]: Configuration file found at: " >> $LOG
	echo "$HOME/.steam-wrapper/steam-wrapper.conf" >> $LOG
elif [[ -f $HOME/.steam-wrapper.conf ]]; then
	source $HOME/.steam-wrapper.conf
	echo -n "steam-wrapper[$VERSION]: Configuration file found at: " >> $LOG
	echo "$HOME/.steam-wrapper.conf" >> $LOG
elif [[ -f /etc/steam-wrapper/steam-wrapper.conf ]]; then
	source /etc/steam-wrapper/steam-wrapper.conf
	echo -n "steam-wrapper[$VERSION]: Configuration file found at: " >> $LOG
	echo "/etc/steam-wrapper/steam-wrapper.conf" >> $LOG
elif [[ -f /etc/steam-wrapper.conf ]]; then
	source /etc/steam-wrapper.conf
	echo -n "steam-wrapper[$VERSION]: Configuration file found at: " >> $LOG
	echo "/etc/steam-wrapper.conf" >> $LOG
else
	DEBUG=1
	USE_RUNTIME=1
	CLOSE_TO_TRAY=1
	echo -n "steam-wrapper[$VERSION]: No configuration file found. " >> $LOG
	echo "Using preset defaults." >> $LOG
fi

# Remove some files that apperantly conflict with native runtimes on ArchLinux
if [[ $DEBUG -eq 1 ]]; then
	echo "steam-wrapper[$VERSION]: Attempting removal of stale libraries..." >> $LOG
fi

# Read for details:
#     https://wiki.archlinux.org/index.php/steam#Steam_runtime_issues
if [[ $DEBUG -eq 1 ]]; then
	find $HOME/.local/share/Steam/ \( -name "libgcc_s.so*" -o -name "libstdc++.so*" -o -name "libxcb.so*" \) -delete -print >> $LOG
else
	find $HOME/.local/share/Steam/ \( -name "libgcc_s.so*" -o -name "libstdc++.so*" -o -name "libxcb.so*" \) -delete
fi

if [[ $DEBUG -eq 1 ]]; then
	echo "steam-wrapper[$VERSION]: Done." >> $LOG
	echo "steam-wrapper[$VERSION]: Launching steam with environment:" >> $LOG
	echo "steam-wrapper[$VERSION]:     STEAM_RUNTIME = ${USE_RUNTIME}" >> $LOG
	echo "steam-wrapper[$VERSION]:     STEAM_FRAME_FORCE_CLOSE = ${CLOSE_TO_TRAY}" >> $LOG
	echo >> $LOG
fi

# Run steam using the wrapper
exec env \
	STEAM_RUNTIME="${USE_RUNTIME}" \
	STEAM_FRAME_FORCE_CLOSE="${CLOSE_TO_TRAY}" \
	steam "$@"
